version: "3"
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark-node
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    container_name: elasticsearch-node
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    deploy:
      resources:
        limits:
          memory: 2g
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.1
    container_name: kibana-node
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"